src/Entity/Society.php
<?php

namespace App\Entity;

use App\Repository\SocietyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SocietyRepository::class)
 */
class Society
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Participant", mappedBy="society")
     */
    private $participant;


    public function __construct()
    {
        $this->participant = new \Doctrine\Common\Collections\ArrayCollection();

    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getParticipant()
    {
        return $this->participant;
    }


    /**
     * @return int
     */
    public function getParticipantlenght() : int
    {
        return sizeof($this->participant);
    }

    /**
     * @param mixed $participant
     */
    public function setParticipant($participant): void
    {
        $this->participant = $participant;
    }

    public function __toString()
    {
        return $this->name;
    }


}

src/Form/SocietyType.php
<?php

namespace App\Form;

use App\Entity\Society;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SocietyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('address')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Society::class,
        ]);
    }
}

src/Controller/SocietyController.php
<?php 
namespace App\Controller;

use App\Entity\Society;
use App\Form\SocietyType;
use App\Repository\SocietyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SocietyController  extends  AbstractController{

    /**
     * @param SocietyRepository $repository
     * @param EntityManagerInterface $em
     */
    private $twig;

    public function __construct(SocietyRepository $repository, EntityManagerInterface $em){
        $this->repository = $repository;
        $this->em =$em;
    }

    /**
     * @Route("/society", name="society.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request) : Response {
        $name = $request->get('name');
        $societies = $paginator->paginate(
            $this->repository->findByParamsQuery($name),
            $request->query->getInt('page',1),
            10);

        return $this->render('society/index.html.twig', [
                'societies' => $societies,
                'filter' => [
                    'name' => $name,
                ]
            ]);
    }

    /**
     * @Route("/society/create", name="society.new")
     * @param Request $request
     * @return Response
     */
    public function create( Request $request) : Response {
        $society = new Society();
        $form  = $this->createForm(SocietyType::class, $society);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->persist($society);
            $this->em->flush();
            return $this->redirectToRoute('society.index');
        }
        return $this->render('society/detail.html.twig', [
            'society' =>$society,
            'form' => $form->createView(),
            'title' => 'Création d\'une société'
        ]);
    }

    /**
     * @Route("/society/{id}", name="society.edit", methods="GET|POST")
     * @param Society $society
     * @param Request $request
     * @return Response
     */
    public function edit(Society $society, Request $request) : Response {
        $form =$this->createForm(SocietyType::class, $society);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $this->em->flush();
            return $this->redirectToRoute('society.index');
        }
        return $this->render('society/detail.html.twig', [
            'society' =>$society,
            'form' => $form->createView(),
            'title' => 'Modification d\'une société'
        ]);
    }

    /**
     * @Route("/society/{id}", name="society.delete", methods="DELETE")
     * @param Society $society
     * @param Request $request
     * @return Response
     */
    public function delete(Society $society, Request $request) : Response {
        if($this->isCsrfTokenValid('delete'.$society->getId(), $request->get('_token'))){
            $this->em->remove($society);
            $this->em->flush();
        }
        return $this->redirectToRoute('society.index');
    }

}

templates/society/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
        <h2>{{ title }}</h2>
        {{ form_start(form) }}
        <div class="row">
            <div class="col-md-4">
                {{ form_row(form.name) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form_row(form.address) }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form_row(form.email) }}
            </div>
        </div>
        <button class="btn btn-primary"> Enregistrer </button>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/society/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Liste des sociétes' %}

{% block body %}
    <div class="container mt-4">
        <div class="text-right">
            <a href="{{ path('society.new') }}" class="btn btn-primary">Créer une société</a>
        </div>
        <form  method="post" action="{{ path('society.index') }}"
                style="display: inline-block">
            <div class="row container mt-4">
                <div class="col-md-10">
                    <input class="form-control" name="name" value="{{ filter.name}}" placeholder="Société">
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary" >rechercher</button>
                </div>
            </div>
        </form>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col" class="sorted column_sort">{{ knp_pagination_sortable(societies, 'Nom', 's.name') }}</th>
                <th scope="col">{{ knp_pagination_sortable(societies, 'Adresse', 's.address') }}</th>
                <th scope="col">{{ knp_pagination_sortable(societies, 'Email', 's.email') }}</th>
                <th scope="col">Nombre employé</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for society in societies %}
                <tr>
                    <td>{{ society.name }}</td>
                    <td>{{ society.address }}</td>
                    <td>{{ society.email }}</td>
                    <td> {{ society.participantlenght }}</td>
                    <td>
                        <a href="{{ path('society.edit', {id : society.id}) }}" class="btn btn-secondary">Editer</a>
                        <form  method="post" action="{{ path('society.delete', {id : society.id}) }}"
                               style="display: inline-block"
                               onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette société ?')">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ society.id) }}">
                            <button class="btn btn-danger"   {% if society.participantlenght > 0 %}  disabled {% endif %}
                                    >Supprimer</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
        <div class="pagination">
            {{ knp_pagination_render(societies) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}

{% endblock %}